### ISSUE TITLE
install fu-liou model 

### ISSUE THREAD

**Issue by pppp-777** [kassick/olam#1]
I'm sorry to bother you.
However, when I run make file , the following error message is displayed:

cd ./lib/src ;make
make[1]: Entering directory '/mnt/d/works/Ed4_LaRC_FuLiou/lib/src'
extras.f90
make[1]: extras.f90: Command not found
make[1]: *** [Makefile:75: extras.o] Error 127
make[1]: Leaving directory '/mnt/d/works/Ed4_LaRC_FuLiou/lib/src'
make: *** [Makefile:7: libsrc] Error 2

What's wrong with it?
Would it be possile to tell me the sollution?

**Comment by kassick** [comment]
Hi!
This repository is just a clone of the original code , I suggest you try compiling the code in https://sourceforge.net/projects/olam-model/

As to what caused the error, I don't know what could have caused it -- probably some command is expanding an empty compiler variable. I tried to find some instructions of how to compile this, but could not find it.
